base: 'https://demoapp.de.test'
languages:
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: global
    languageId: 0
rootPageId: 2
websiteTitle: ''
