base: 'https://demoapp.de.test'
dependencies:
  - typo3/fluid-styled-content-css
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 2
websiteTitle: demoapp
