base: 'https://demoapp.de.test'
dependencies:
  - friendsoftypo3/headless
frontendBase: ''
headless: 0
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 2
websiteTitle: demoapp
